- generate-types.js
- index.html
- package-lock.json
- package.json
- src/api/auth/authGet.ts
- src/api/auth/authLoginPost.ts
- src/api/auth/authSignupPost.ts
- src/api/base.ts
- src/components/LayoutWrapper/LayoutWrapper.module.css
- src/components/LayoutWrapper/LayoutWrapper.tsx
- src/constants/constants.ts
- src/pages/FeedPage/FeedPage.ts
- src/router.tsx
- src/stores/OwnProfileStore.ts
- src/types/PageType.ts
- src/types/domain.ts
- src/utils/isEmpty.ts
- src/utils/isObject.ts
> prepare auth env & check auth for profile in header

- package-lock.json
- src/api/auth/authDelete.ts
- src/components/AuthModal/AuthModal.tsx
- src/components/AuthModal/components/LoginForm.tsx
- src/components/AuthModal/components/ProfileTypeSegmented.tsx
- src/components/AuthModal/components/SignupForm.tsx
- src/components/AuthModal/constants.ts
- src/components/AuthModal/hooks/useLoginHandler.ts
- src/components/AuthModal/hooks/useSignupHandler.ts
- src/components/LayoutWrapper/LayoutWrapper.tsx
- src/components/LayoutWrapper/useAuthModal.ts
- src/router.tsx
- src/types/domain.ts
> login + signup

- package-lock.json
- package.json
- src/api/departments/departmentsGet.ts
- src/api/levels/levelsGet.ts
- src/api/schools/schoolsGet.ts
- src/components/AuthModal/components/SignupForm.tsx
- src/constants/constants.ts
- src/queries/useDepartments.ts
- src/queries/useLevels.ts
- src/queries/useSchools.ts
- src/types/domain.ts
> selectors for levels, departments, schools

- src/api/auth/authDelete.ts
- src/constants/constants.ts
> auth delete route path and base url fix

- src/api/profiles/profilesProfileIdFollowDelete.ts
- src/api/profiles/profilesProfileIdFollowPost.ts
- src/api/profiles/profilesProfileIdGet.ts
- src/pages/ProfilePage/components/ProfileInfoCard/ProfileInfoCard.tsx
- src/pages/ProfilePage/components/SubscribeButton/SubscribeButton.tsx
- src/types/domain.ts
> subscribe & unsub

- src/api/profiles/profilesProfileIdDelete.ts
- src/pages/ProfilePage/components/EditProfileModal/EditProfileModal.tsx
> delete own profile

- src/api/profiles/profilesProfileIdFollowersGet.ts
- src/api/profiles/profilesProfileIdSubscriptionsGet.ts
- src/components/GenericProfileCommunityColumn/GenericProfileCommunityColumn.tsx
- src/components/GenericProfileCommunityColumn/components/ProfileCommunityInfoCard/ProfileCommunityInfoCard.module.css
- src/components/GenericProfileCommunityColumn/components/ProfileCommunityInfoCard/ProfileCommunityInfoCard.tsx
- src/components/ProfilesListModal/ProfilesListModal.tsx
- src/pages/CommunityPage/CommunityPage.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/queries/useCommunityFollowers.ts
- src/queries/useProfileFollowers.ts
- src/queries/useProfileSubscriptions.ts
> Sub modals

- mock/communities.ts
- package-lock.json
- package.json
- src/components/LayoutWrapper/LayoutWrapper.tsx
- src/pages/CommunitiesPage/CommunitiesPage.tsx
- src/pages/CommunitiesPage/components/AddCommunityModal/AddCommunityModal.tsx
- src/pages/CommunitiesPage/components/CommunitiesGallery/CommunitiesGallery.module.css
- src/pages/CommunitiesPage/components/CommunitiesGallery/CommunitiesGallery.tsx
- src/queries/useCommunities.ts
- src/router.tsx
- src/utils/generateCommunityId.ts
> communities gallery & create

- mock/communities.ts
- src/api/communities/communitiesCommunityIdAdminsEligibleGet.ts
- src/api/communities/communitiesCommunityIdAdminsGet.ts
- src/api/communities/communitiesCommunityIdAdminsProfileIdDelete.ts
- src/api/communities/communitiesCommunityIdAdminsProfileIdPost.ts
- src/components/GenericProfileCommunityColumn/components/AdminsModal/AdminsModal.module.css
- src/components/GenericProfileCommunityColumn/components/AdminsModal/AdminsModal.tsx
- src/components/GenericProfileCommunityColumn/components/AdminsModalUserItem/AdminsModalUserItem.tsx
- src/components/GenericProfileCommunityColumn/components/ProfileCommunityInfoCard/ProfileCommunityInfoCard.tsx
- src/queries/useCommunityAdmins.ts
- src/queries/useCommunityEligibleAdmins.ts
> list add & delete admins

- mock/posts.ts
- mock/profiles.ts
- package-lock.json
- package.json
- src/api/posts/postsPostIdLikesDelete.ts
- src/api/posts/postsPostIdLikesGet.ts
- src/api/posts/postsPostIdLikesPost.ts
- src/api/profiles/profilesProfileIdPostsGet.ts
- src/components/GenericProfileCommunityColumn/components/AdminsModal/AdminsModal.tsx
- src/components/PostGeneric/PostGeneric.module.css
- src/components/PostGeneric/PostGeneric.tsx
- src/components/PostGeneric/components/PostActions/PostActions.module.css
- src/components/PostGeneric/components/PostActions/PostActions.tsx
- src/components/PostGeneric/components/PostHeaderCommunity/PostHeaderCommunity.tsx
- src/components/PostGeneric/components/PostHeaderProfile/PostHeaderProfile.tsx
- src/components/PostGeneric/utils/postGuards.ts
- src/components/StaffBadge/StaffBadge.module.css
- src/components/StaffBadge/StaffBadge.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/pages/ProfilePage/components/ProfileFeedColumn/ProfileFeedColumn.tsx
- src/queries/usePostLikes.ts
- src/queries/useProfilePosts.ts
- src/types/domain.ts
- src/utils/dateAsRelativeText.ts
> post component

- mock/events.ts
- src/api/events/eventsGet.ts
- src/components/LayoutWrapper/LayoutWrapper.tsx
- src/pages/EventsPage/EventsPage.tsx
- src/pages/EventsPage/components/EventsGallery/EventsGallery.module.css
- src/pages/EventsPage/components/EventsGallery/EventsGallery.tsx
- src/queries/useEvents.ts
- src/router.tsx
- src/utils/eventGuards.ts
> events page

- mock/profiles.ts
- src/api/communities/communitiesCommunityIdEventsGet.ts
- src/api/profiles/profilesProfileIdEventsGet.ts
- src/components/EventCard/EventCard.tsx
- src/components/EventModal/EventModal.tsx
- src/components/EventsColumn/EventsColumn.tsx
- src/components/GenericProfileCommunityColumn/GenericProfileCommunityColumn.tsx
- src/pages/CommunityPage/CommunityPage.tsx
- src/pages/EventsPage/components/EventsGallery/EventsGallery.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/queries/useCommunityEvents.ts
- src/queries/useProfileEvents.ts
> events on community and profile pages

- src/api/communities/communitiesCommunityIdPostsPost.ts
- src/api/posts/postsPostIdImgPut.ts
- src/api/profiles/profilesProfileIdPostsPost.ts
- src/components/AuthModal/components/LoginForm.tsx
- src/components/AuthModal/components/SignupForm.tsx
- src/components/CommunityAvatar/CommunityAvatar.tsx
- src/components/PostEditor/PostEditor.module.css
- src/components/PostEditor/PostEditor.tsx
- src/components/PostEditor/components/AddEventPopover/AddEventPopover.module.css
- src/components/PostEditor/components/AddEventPopover/AddEventPopover.tsx
- src/components/PostEditor/components/AddImagePopover/AddImagePopover.tsx
- src/components/PostEditor/components/EventPreview/EventPreview.module.css
- src/components/PostEditor/components/EventPreview/EventPreview.tsx
- src/components/PostEditor/utils.ts
- src/components/ProfileAvatar/ProfileAvatar.tsx
- src/pages/CommunityPage/CommunityPage.tsx
- src/pages/CommunityPage/components/CommunityFeedColumn/CommunityFeedColumn.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/pages/ProfilePage/components/ProfileFeedColumn/ProfileFeedColumn.tsx
- src/utils/getBase64Upload.ts
closes #61 
partly #62 & #63, display in separate pull request
> add profile/community posts

- package-lock.json
- package.json
- src/api/communities/communitiesCommunityIdPostsGet.ts
- src/api/posts/feedGet.ts
- src/api/profiles/profilesProfileIdPostsGet.ts
- src/components/PostGeneric/PostGeneric.tsx
- src/components/PostGeneric/components/PostActions/PostActions.tsx
- src/components/PostsFeed/PostsFeed.tsx
- src/pages/CommunityPage/components/CommunityFeedColumn/CommunityFeedColumn.tsx
- src/pages/FeedPage/FeedPage.tsx
- src/pages/FeedPage/components/FeedColumn/FeedColumn.tsx
- src/pages/PostPage/PostPage.tsx
- src/pages/PostPage/components/MorePostsColumn/MorePostsColumn.tsx
- src/pages/ProfilePage/components/ProfileFeedColumn/ProfileFeedColumn.tsx
- src/queries/useFeed.ts
- src/stores/FeedStore.ts
- src/types/domain.ts
- vite.config.ts
> Dynamic feed

- src/api/events/eventsEventIdSubscribeDelete.ts
- src/api/events/eventsEventIdSubscribePost.ts
- src/components/CreateEventModal/CreateEventModal.tsx
- src/components/EventModal/EventModal.tsx
- src/components/EventSubscribeButton/EventSubscribeButton.tsx
- src/components/EventsColumn/EventsColumn.tsx
- src/components/SubscribeButton/SubscribeButton.tsx
- src/types/domain.ts
> fix not able to add event if none

- src/components/ProfilesListModal/ProfilesListModal.tsx
> clickable profiles in modals

- src/components/SubscribeButton/SubscribeButton.tsx
> Fixed subscribe bug

- src/components/PostGeneric/PostGeneric.tsx
- src/components/PostGeneric/components/PostActions/PostActions.tsx
- src/components/PostsFeed/PostsFeed.tsx
- src/stores/FeedStore.ts
> fix likes in feeds

- src/components/CreateEventModal/CreateEventModal.tsx
> add hour to event

- src/components/GenericProfileCommunityColumn/GenericProfileCommunityColumn.tsx
- src/components/GenericProfileCommunityColumn/components/CommunityTagsCard/CommunityTagsCard.module.css
- src/components/GenericProfileCommunityColumn/components/CommunityTagsCard/CommunityTagsCard.tsx
- src/components/GenericProfileCommunityColumn/components/ProfileTypeCards/ProfileTypeCards.tsx
- src/pages/CommunityPage/components/EditCommunityModal/EditCommunityModal.tsx
- src/types/domain.ts
> community tags

- src/api/posts/postsPostIdCommentsCommentIdDelete.ts
- src/api/posts/postsPostIdCommentsCommentIdPatch.ts
- src/api/posts/postsPostIdDelete.ts
- src/api/posts/postsPostIdPatch.ts
- src/components/CommentGeneric/CommentGeneric.module.css
- src/components/CommentGeneric/CommentGeneric.tsx
- src/components/CommentGeneric/components/CommentHeader/CommentHeader.tsx
- src/components/CommentsFeed/CommentsFeed.tsx
- src/components/CommentsFeed/CommentsFeedPure.tsx
- src/components/PostEditableDropdown/PostEditableDropdown.tsx
- src/components/PostEditor/PostEditor.tsx
- src/components/PostGeneric/PostGeneric.module.css
- src/components/PostGeneric/PostGeneric.tsx
- src/components/PostGeneric/components/PostHeaderCommunity/PostHeaderCommunity.tsx
- src/components/PostGeneric/components/PostHeaderProfile/PostHeaderProfile.tsx
- src/components/PostsFeed/PostsFeed.tsx
- src/pages/CommunityPage/components/CommunityFeedColumn/CommunityFeedColumn.tsx
- src/pages/FeedPage/components/FeedColumn/FeedColumn.tsx
- src/pages/PostPage/PostPage.tsx
- src/pages/ProfilePage/components/ProfileFeedColumn/ProfileFeedColumn.tsx
- src/queries/useCommunityEvents.ts
- src/queries/useProfileEvents.ts
- src/stores/CommentsFeedStore.ts
- src/stores/FeedStore.ts
- src/types/domain.ts
> edit delete comments

- src/components/GenericProfileCommunityColumn/components/CommunityTagsCard/CommunityTagsCard.tsx
- src/components/GenericProfileCommunityColumn/components/ProfileTypeCards/ProfileTypeCards.tsx
- src/components/InterestTagsSelect/InterestTagsSelect.tsx
> fix dying interests

- src/api/posts/postsPostIdImgDelete.ts
- src/components/PostEditor/PostEditor.tsx
- src/components/PostGeneric/PostGeneric.tsx
- src/pages/PostPage/PostPage.tsx
> fix image not deleting & redirect after post delete
